#!/bin/bash
# Generates .env files with URLs appropriate for the current environment.
# In Codespaces, uses the forwarded-port URLs; otherwise falls back to localhost.
# Safe to run multiple times — idempotent.
set -euo pipefail

WORKSPACE="/workspaces/byggmester-bob"

if [ -n "${CODESPACE_NAME:-}" ] && [ -n "${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN:-}" ]; then
  FRONTEND_URL="https://${CODESPACE_NAME}-5173.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
  BACKEND_URL="https://${CODESPACE_NAME}-3001.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
else
  FRONTEND_URL="http://localhost:5173"
  BACKEND_URL="http://localhost:3001"
fi

# frontend/.env — VITE_API_URL is intentionally empty so all /api/* requests
# go through the Vite dev-server proxy (vite.config.ts server.proxy).  The
# proxy rewrites them to http://localhost:3001 inside the container, keeping
# the browser on a single origin and avoiding cross-site cookie problems.
cat > "${WORKSPACE}/frontend/.env" <<EOF
# Auto-generated by .devcontainer/setup-env.sh — do not commit
# Empty value: the Vite proxy routes /api and /health to the backend
VITE_API_URL=
EOF

# backend/.env — write once; on subsequent starts only update CORS_ORIGIN
# so a developer's custom SESSION_SECRET is preserved across restarts.
if [ ! -f "${WORKSPACE}/backend/.env" ]; then
  cat > "${WORKSPACE}/backend/.env" <<EOF
# Auto-generated by .devcontainer/setup-env.sh — do not commit
PORT=3001
NODE_ENV=development
DATABASE_URL=postgresql://devuser:devpassword@db:5432/devdb?sslmode=disable
SESSION_SECRET=dev-only-change-in-production
CORS_ORIGIN=${FRONTEND_URL}
EOF
else
  # Keep CORS_ORIGIN in sync with the (possibly updated) Codespace URL
  if grep -q "^CORS_ORIGIN=" "${WORKSPACE}/backend/.env"; then
    sed -i "s|^CORS_ORIGIN=.*$|CORS_ORIGIN=${FRONTEND_URL}|" "${WORKSPACE}/backend/.env"
  else
    echo "CORS_ORIGIN=${FRONTEND_URL}" >> "${WORKSPACE}/backend/.env"
  fi
fi

echo "Env files written. FRONTEND_URL=${FRONTEND_URL}  BACKEND_URL=${BACKEND_URL}"
